<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@page import="Modelo.dto.SolicitudCreditoDTO"%><%@page import="Modelo.dto.DetalleCreditoDTO"%><%@page import="java.util.List"%><%@page import="Modelo.dto.ProductoDTO"%>
<%if(session.getAttribute("idUsuario")==null){response.sendRedirect(request.getContextPath()+"/index.jsp");return;} List<SolicitudCreditoDTO> solicitudes=(List<SolicitudCreditoDTO>)request.getAttribute("solicitudes"); DetalleCreditoDTO detalle=(DetalleCreditoDTO)request.getAttribute("detalleCredito"); String ok=(String)request.getAttribute("ok"); String error=(String)request.getAttribute("error"); boolean staff=session.getAttribute("idRol")!=null && (((Integer)session.getAttribute("idRol"))==1 || ((Integer)session.getAttribute("idRol"))==2 || ((Integer)session.getAttribute("idRol"))==3);%>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estado del crédito | DebiCom</title><link rel="stylesheet" href="<%=request.getContextPath()%>/vista/CSS/styles.css"></head><body class="app-body"><div class="app-shell"><%@include file="WEB-INF/jspf/sidebar.jspf" %><main class="app-main"><section class="page-content">
<div class="page-heading"><div><h1><%=detalle!=null?"Detalle de crédito":"Estado de mis créditos"%></h1><p><%=detalle!=null?"Consulta productos, saldo y registra el pago del crédito seleccionado.":"Consulta el estado de tus solicitudes."%></p></div></div>
<%if("pago".equals(ok)){%><article class="card" style="margin-bottom:16px;border-left:4px solid #2ecc71;"><strong>El pago fue aplicado correctamente al crédito seleccionado.</strong></article><%}else if("credito-creado".equals(ok)){%><article class="card" style="margin-bottom:16px;border-left:4px solid #2ecc71;"><strong>El crédito fue otorgado y quedó aprobado correctamente.</strong></article><%}%><%if(error!=null&&!error.isBlank()){%><article class="card" style="margin-bottom:16px;border-left:4px solid #e74c3c;"><strong>Error:</strong> <%=error%></article><%}%>
<%if(detalle!=null){SolicitudCreditoDTO s=detalle.getSolicitud();%>
<article class="card"><div class="metric-row"><article class="metric"><span class="label">Crédito</span><strong>#<%=s.getIdSolicitud()%></strong></article><article class="metric"><span class="label">Cliente</span><strong><%=s.getCliente()%></strong></article><article class="metric"><span class="label">Tienda</span><strong><%=s.getTienda()%></strong></article><article class="metric"><span class="label">Estado</span><strong><%=s.getEstado()%></strong></article></div><p><b>Monto:</b> $<%=s.getMontoTotal()%> · <b>Saldo:</b> $<%=s.getSaldoPendiente()%> · <b>Vencimiento:</b> <%=s.getFechaVencimiento()%></p><p><b>Fecha creación:</b> <%=s.getFechaSolicitud()%> · <b>Aprobación:</b> <%=s.getFechaAprobacion()==null?"—":s.getFechaAprobacion()%></p><p><b>Observaciones:</b> <%=s.getObservaciones()==null?"":s.getObservaciones()%></p></article>
<article class="card"><h2>Productos incluidos</h2><div class="table-wrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio unitario</th><th>Subtotal</th><th>Stock actual</th></tr></thead><tbody><%for(ProductoDTO p:detalle.getProductos()){%><tr><td><%=p.getNombre()%></td><td><%=p.getCantidad()%></td><td>$<%=p.getPrecioUnitario()%></td><td>$<%=p.getSubtotal()%></td><td><%=p.getStock()%></td></tr><%}%></tbody></table></div></article>
<%if(staff && s.getSaldoPendiente()!=null && s.getSaldoPendiente().compareTo(java.math.BigDecimal.ZERO)>0){%><article class="card"><h2>Registrar pago parcial</h2><p>El sistema ya conoce el crédito <b>#<%=s.getIdSolicitud()%></b> y su comprador. Solo necesitas indicar el monto del abono.</p><form class="dark-grid" method="post" action="<%=request.getContextPath()%>/vendedor/pagos/registrar"><input type="hidden" name="idSolicitud" value="<%=s.getIdSolicitud()%>"><label>Monto a pagar<input type="number" name="monto" min="0.01" max="<%=s.getSaldoPendiente()%>" step="0.01" required placeholder="0.00"></label><div class="form-actions"><button class="button primary" type="submit">Registrar pago parcial</button><a class="button secondary" href="<%=request.getContextPath()%>/vendedor/creditos-pendientes">Volver</a></div></form></article><%}%>
<%}else{%><article class="card"><div class="table-wrap"><table><thead><tr><th>Crédito</th><th>Tienda</th><th>Monto</th><th>Saldo</th><th>Solicitud</th><th>Vencimiento</th><th>Estado</th></tr></thead><tbody><%if(solicitudes==null||solicitudes.isEmpty()){%><tr><td colspan="7">No hay solicitudes registradas.</td></tr><%}else for(SolicitudCreditoDTO s:solicitudes){%><tr><td>#<%=s.getIdSolicitud()%></td><td><%=s.getTienda()%></td><td>$<%=s.getMontoTotal()%></td><td>$<%=s.getSaldoPendiente()%></td><td><%=s.getFechaSolicitud()%></td><td><%=s.getFechaVencimiento()%></td><td><%=s.getEstado()%></td></tr><%}%></tbody></table></div></article><%}%>
</section></main></div></body></html>
